[package]
name = "made-up"
version = "0.1.0"
authors = ["Dylan Maccora <maccora17@gmail.com>"]

[dependencies]
pulldown-cmark = "0.0.14"
walkdir = "1.*"
serde_json = "^1.0"
log = "0.3"
serde = "^1.0"
serde_yaml = "0.7"
serde_derive = "1.0.2"
clap = "2.24"
error-chain = "0.10"
handlebars = "0.29.1"
